# Generated by Django 4.0 on 2024-07-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Narx $da'),
        ),
    ]
