# Generated by Django 4.0 on 2024-07-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chiqish',
            field=models.BooleanField(default=True, verbose_name='Ekranga chiqsinmi?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.CharField(choices=[('iqtisod', 'iqtisod'), ('jaxon', 'jaxon'), ('ozbekiston', 'ozbekiston')], default='ozbekiston', max_length=100),
        ),
    ]
