# Generated by Django 4.0 on 2024-07-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.CharField(choices=[('ozbekiston', 'ozbekiston'), ('iqtisod', 'iqtisod'), ('jaxon', 'jaxon')], default='ozbekiston', max_length=100),
        ),
    ]
