# Generated by Django 4.0 on 2024-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.CharField(choices=[('iqtisod', 'iqtisod'), ('ozbekiston', 'ozbekiston'), ('jaxon', 'jaxon')], default='ozbekiston', max_length=100),
        ),
    ]
